-- 1. 직급 테이블 생성
CREATE TABLE POSITION (
    POSITION_NUM   NUMBER PRIMARY KEY,
    POSITION_NAME  VARCHAR2(30) NOT NULL UNIQUE,
    POSITION_SAL   NUMBER(10) NOT NULL
);

-- 2. 시퀀스 생성 (10,20,30... 식으로 증가)
CREATE SEQUENCE SEQ_POSITION
START WITH 10
INCREMENT BY 10
NOCACHE
NOCYCLE;

-- 3. 초기 데이터 등록
INSERT INTO POSITION (POSITION_NUM, POSITION_NAME, POSITION_SAL) VALUES (SEQ_POSITION.NEXTVAL, '사원', 150);
INSERT INTO POSITION (POSITION_NUM, POSITION_NAME, POSITION_SAL) VALUES (SEQ_POSITION.NEXTVAL, '대리', 200);
INSERT INTO POSITION (POSITION_NUM, POSITION_NAME, POSITION_SAL) VALUES (SEQ_POSITION.NEXTVAL, '과장', 300);
INSERT INTO POSITION (POSITION_NUM, POSITION_NAME, POSITION_SAL) VALUES (SEQ_POSITION.NEXTVAL, '차장', 400);
INSERT INTO POSITION (POSITION_NUM, POSITION_NAME, POSITION_SAL) VALUES (SEQ_POSITION.NEXTVAL, '상무', 500);

COMMIT;

ALTER TABLE USERTEST
ADD CONSTRAINT FK_USERTEST_POSITION
FOREIGN KEY (POSITION_NUM)
REFERENCES POSITION(POSITION_NUM);