-- 인사발령 이력 테이블
CREATE TABLE HR_APPOINTMENT_HISTORY (
    HISTORY_ID        NUMBER PRIMARY KEY,
    TARGET_USER_ID    NUMBER NOT NULL,             -- 변경 대상 사원 USER_ID
    CHANGE_TYPE       VARCHAR2(20) NOT NULL,       -- DEPT / POSITION / EMP_STATUS
    BEFORE_VALUE      VARCHAR2(100),               -- 변경 전 값(코드/번호)
    AFTER_VALUE       VARCHAR2(100),               -- 변경 후 값(코드/번호)
    BEFORE_LABEL      VARCHAR2(100),               -- 변경 전 표시명(예: 개발팀, 대리, 재직)
    AFTER_LABEL       VARCHAR2(100),               -- 변경 후 표시명
    CHANGE_REASON     VARCHAR2(200),               -- 사유(선택)
    CHANGED_BY        NUMBER NOT NULL,             -- 변경한 관리자 USER_ID
    SOURCE_MENU       VARCHAR2(30) DEFAULT 'USER_MANAGE' NOT NULL,
    LOGIN_LOG_ID      NUMBER,                      -- 로그인 로그 연결 (선택)
    CHANGED_AT        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_HR_APPT_CHANGE_TYPE CHECK (CHANGE_TYPE IN ('DEPT', 'POSITION', 'EMP_STATUS'))
);

-- 시퀀스
CREATE SEQUENCE HR_APPOINTMENT_HISTORY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 인덱스 (조회 성능용)
CREATE INDEX IDX_HR_APPT_TARGET_USER ON HR_APPOINTMENT_HISTORY(TARGET_USER_ID);
CREATE INDEX IDX_HR_APPT_CHANGED_AT   ON HR_APPOINTMENT_HISTORY(CHANGED_AT);
CREATE INDEX IDX_HR_APPT_CHANGE_TYPE  ON HR_APPOINTMENT_HISTORY(CHANGE_TYPE);

-- FK (USERTEST 기준)
ALTER TABLE HR_APPOINTMENT_HISTORY
ADD CONSTRAINT FK_HR_APPT_TARGET_USER
FOREIGN KEY (TARGET_USER_ID) REFERENCES USERTEST(USER_ID);

ALTER TABLE HR_APPOINTMENT_HISTORY
ADD CONSTRAINT FK_HR_APPT_CHANGED_BY
FOREIGN KEY (CHANGED_BY) REFERENCES USERTEST(USER_ID);

COMMIT;