CREATE TABLE ATTENDANCE (
    ATT_ID      NUMBER PRIMARY KEY,
    USER_ID     NUMBER NOT NULL,
    ATT_DATE    DATE DEFAULT TRUNC(SYSDATE) NOT NULL, -- 근태 기준일(날짜만)
    CHECK_IN    DATE,
    CHECK_OUT   DATE,

    IN_STATUS   NUMBER(1) DEFAULT 0 NOT NULL,  -- 0:미정, 1:정상출근, 2:지각
    OUT_STATUS  NUMBER(1) DEFAULT 0 NOT NULL,  -- 0:미정, 1:정상퇴근, 2:조퇴, 3:연장

    CONSTRAINT FK_ATT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERTEST(USER_ID),

    CONSTRAINT CK_ATT_IN_STATUS
        CHECK (IN_STATUS IN (0,1,2)),

    CONSTRAINT CK_ATT_OUT_STATUS
        CHECK (OUT_STATUS IN (0,1,2,3)),

    -- 같은 사원이 같은 날짜에 1건만 입력되게 (중요)
    CONSTRAINT UK_ATT_USER_DATE UNIQUE (USER_ID, ATT_DATE)
);
CREATE SEQUENCE ATT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;